### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by aspauldingcode** [hraban/mac-app-util#9] opened 2024-10-30 17:16 UTC
I tried installing today.
Both for nix-darwin and for home-manager.

The nix-darwin works fine.
The home-manager module for mac-app-util would give me the following the answer:

```
setting nvram variables...
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
.: replacing existing signature
Activating home-manager configuration for alex
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLaunchAgents
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
Activating linkGeneration
Cleaning up orphan links from /Users/alex
No change so reusing latest profile generation 352
Creating home file links in /Users/alex
Activating onFilesChange
Activating rsync-home-manager-applications
Activating setupLaunchAgents
Activating trampolineApps
Unhandled SB-EXT:DELETE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=259 "main thread" RUNNING
                                                {7004AB0143}>:
  Could not delete the file
  "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/CodeResources":

    Permission denied

Backtrace for: #<SB-THREAD:THREAD tid=259 "main thread" RUNNING {7004AB0143}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-EXT:DELETE-FILE-ERROR {7005FEB143}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-EXT:DELETE-FILE-ERROR {7005FEB143}>)
2: (INVOKE-DEBUGGER #<SB-EXT:DELETE-FILE-ERROR {7005FEB143}>)
3: (ERROR SB-EXT:DELETE-FILE-ERROR :PATHNAME "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/CodeResources" :MESSAGE "Permission denied")
4: (SB-IMPL::FILE-PERROR "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/CodeResources" 13 SB-EXT:DELETE-FILE-ERROR)
5: (DELETE-FILE #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/CodeResources")
6: ((FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) #<FUNCTION (FLET SB-IMPL::ONE-ITER :IN SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR) {1011C1D5B}>)
7: (SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR #<FUNCTION (FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) {1011C1C8B}> "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/" T)
8: (SB-EXT:MAP-DIRECTORY #<FUNCTION (LAMBDA (SB-IMPL::FILE) :IN SB-EXT:DELETE-DIRECTORY) {7005FE8E8B}> #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/" :FILES T :DIRECTORIES NIL :CLASSIFY-SYMLINKS NIL :ERRORP T)
9: ((LABELS SB-IMPL::RECURSE :IN SB-EXT:DELETE-DIRECTORY) #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/_CodeSignature/")
10: ((FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) #<FUNCTION (FLET SB-IMPL::ONE-ITER :IN SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR) {1011C1AFB}>)
11: (SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR #<FUNCTION (FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) {1011C1A2B}> "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/" T)
12: (SB-EXT:MAP-DIRECTORY #<FUNCTION (LAMBDA (SB-IMPL::SUB) :IN SB-EXT:DELETE-DIRECTORY) {7005FE6DFB}> #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/" :FILES NIL :DIRECTORIES T :CLASSIFY-SYMLINKS NIL :ERRORP T)
13: ((LABELS SB-IMPL::RECURSE :IN SB-EXT:DELETE-DIRECTORY) #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/Contents/")
14: ((FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) #<FUNCTION (FLET SB-IMPL::ONE-ITER :IN SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR) {1011C189B}>)
15: (SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR #<FUNCTION (FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) {1011C17CB}> "/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/" T)
16: (SB-EXT:MAP-DIRECTORY #<FUNCTION (LAMBDA (SB-IMPL::SUB) :IN SB-EXT:DELETE-DIRECTORY) {7005FE654B}> #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/" :FILES NIL :DIRECTORIES T :CLASSIFY-SYMLINKS NIL :ERRORP T)
17: ((LABELS SB-IMPL::RECURSE :IN SB-EXT:DELETE-DIRECTORY) #P"/Users/alex/Applications/Home Manager Trampolines/Visual Studio Code.app/")
18: ((FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) #<FUNCTION (FLET SB-IMPL::ONE-ITER :IN SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR) {1011C163B}>)
19: (SB-IMPL::CALL-WITH-NATIVE-DIRECTORY-ITERATOR #<FUNCTION (FLET SB-IMPL::ITERATE :IN SB-EXT:MAP-DIRECTORY) {1011C156B}> "/Users/alex/Applications/Home Manager Trampolines/" T)
20: (SB-EXT:MAP-DIRECTORY #<FUNCTION (LAMBDA (SB-IMPL::SUB) :IN SB-EXT:DELETE-DIRECTORY) {7005FE599B}> #P"/Users/alex/Applications/Home Manager Trampolines/" :FILES NIL :DIRECTORIES T :CLASSIFY-SYMLINKS NIL :ERRORP T)
21: ((LABELS SB-IMPL::RECURSE :IN SB-EXT:DELETE-DIRECTORY) #P"/Users/alex/Applications/Home Manager Trampolines/")
22: (SYNC-TRAMPOLINES "/Users/alex/Applications/Home Manager Apps" "/Users/alex/Applications/Home Manager Trampolines")
23: (SB-INT:SIMPLE-EVAL-IN-LEXENV (MAIN) #<NULL-LEXENV>)
24: (SB-EXT:EVAL-TLF (MAIN) 47 NIL)
25: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (MAIN) 47)
26: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (MAIN) :CURRENT-INDEX 47)
27: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {1011C0E1B}> #<SB-C::SOURCE-INFO {7004B17D13}> SB-C::INPUT-ERROR-IN-LOAD)
28: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
29: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}> NIL)
30: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {1011C09EB}> #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}> NIL #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}>)
31: (LOAD #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
32: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped" {7004AB1B93}>)
33: ((FLET SB-UNIX::BODY :IN SB-IMPL::PROCESS-SCRIPT))
34: ((FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-IMPL::PROCESS-SCRIPT))
35: (SB-IMPL::PROCESS-SCRIPT "/nix/store/r9hq11bjjg474q5g4316kpb6a9gqw3dm-mac-app-util/bin/.mac-app-util-wrapped")
36: (SB-IMPL::TOPLEVEL-INIT)
37: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
38: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
39: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting

```

my nixos flake:

```
{
  description = "Universal Flake by Alex - macOS and NixOS";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05"; # Set to the desired stable version
    unstable_nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager/release-24.05";
      inputs.nixpkgs.follows = "nixpkgs"; # Ensure home-manager follows the stable nixpkgs version
    };
    nix-colors.url = "github:misterio77/nix-colors";

    nix-darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs"; # Follows the stable nixpkgs version
    };

    nixvim = {
      url = "github:nix-community/nixvim";
    };

    mobile-nixos = {
      url = "github:NixOS/mobile-nixos";
      flake = false;
    };

    apple-silicon = {
      url = "github:tpwrules/nixos-apple-silicon";
      inputs.nixpkgs.follows = "nixpkgs"; # Follows the stable nixpkgs version
    };

    nur = {
      url = "github:nix-community/nur";
    };

    nix-std = {
      url = "github:chessai/nix-std";
    };

    nixtheplanet = {
      url = "github:matthewcroughan/nixtheplanet";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    mac-app-util = {
      url = "github:hraban/mac-app-util";
    };
  };

  outputs = {
    self,
    nixpkgs,
    unstable_nixpkgs,
    nix-darwin,
    home-manager,
    nixvim,
    flake-parts,
    nix-colors,
    mobile-nixos,
    apple-silicon,
    nur,
    nix-std,
    nixtheplanet,
    agenix,
    mac-app-util,
  }:
  let
    inherit (self) inputs;
    std = nix-std.lib;
    # Define common specialArgs for nixosConfigurations and homeConfigurations
    commonSpecialArgs = {
      inherit
        inputs
        nix-darwin
        nixvim
        home-manager
        flake-parts
        nix-colors
        apple-silicon
        nur
        self
        std
        nixtheplanet
        ;
    };
    commonExtraSpecialArgs = {
      inherit
        inputs
        nix-darwin
        nixvim
        flake-parts
        nix-colors
        apple-silicon
        nur
        self
        std
        nixtheplanet
        ;
    };
    systems = [
      "x86_64-linux"
      "aarch64-linux"
      "x86_64-darwin"
      "aarch64-darwin"
    ];
    eachSystem = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

    # Define NixOS configurations
    nixosConfigurations = {
      NIXSTATION64 = nixpkgs.lib.nixosSystem {
        pkgs = import nixpkgs {
          system = "x86_64-linux";
          config = {
            allowUnfree = true;
            permittedInsecurePackages = [ "electron-19.1.9" ];
          };
          overlays = [
            inputs.nur.overlay
            (final: _prev: {
              unstable = import unstable_nixpkgs {
                inherit (final) system config;
              };
            })
          ];
        };
        specialArgs = commonSpecialArgs; # // { extraPkgs = [ mobile-nixos ]; };
        modules = [
          ./system/NIXSTATION64/configuration-NIXSTATION64.nix
          home-manager.nixosModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              users.alex = import ./users/alex/NIXSTATION64/home-NIXSTATION64.nix;
              # Optionally, use home-manager.extraSpecialArgs to pass
              # arguments to home.nix
              extraSpecialArgs = commonExtraSpecialArgs;
              backupFileExtension = "backup";
            };
          }
          agenix.nixosModules.default
        ];
      };
      NIXEDUP = nixpkgs.lib.nixosSystem {
        pkgs = nixpkgs.legacyPackages.aarch64-linux;
        specialArgs = commonSpecialArgs;
        modules = [ 
          ./system/NIXEDUP/configuration-NIXEDUP.nix 
          agenix.nixosModules.default
        ];
      };
      NIXY2 = nixpkgs.lib.nixosSystem {
        pkgs = import nixpkgs {
          system = "aarch64-linux";
          config = {
            allowUnfree = true;
            permittedInsecurePackages = [ "electron-19.1.9" ];
          };
          overlays = [
            inputs.nur.overlay
            (final: _prev: {
              unstable = import unstable_nixpkgs {
                inherit (final) system config;
              };
            })
          ];
        };
        specialArgs = commonSpecialArgs; # // { extraPkgs = [ mobile-nixos ]; };
        modules = [
          ./system/NIXY2/configuration-NIXY2.nix
          home-manager.nixosModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              users.alex = import ./users/alex/NIXY2/home-NIXY2.nix;
              # Optionally, use home-manager.extraSpecialArgs to pass
              # arguments to home.nix
              extraSpecialArgs = commonExtraSpecialArgs;
              backupFileExtension = "backup";
            };
          }
          agenix.nixosModules.default
        ];
      };
    };

    # Define Darwin (macOS) configurations
    darwinConfigurations = {
      NIXY = nix-darwin.lib.darwinSystem {
        pkgs = import nixpkgs {
          system = "aarch64-darwin";
          config.allowUnfree = true;
          overlays = [
            inputs.nur.overlay
            (final: _prev: {
              unstable = import unstable_nixpkgs {
                inherit (final) system config;
              };
            })
          ];
        };
        specialArgs = commonSpecialArgs;
        modules = [
          ./system/NIXY/darwin-configuration-NIXY.nix
          mac-app-util.darwinModules.default
          home-manager.darwinModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              # Optionally, use home-manager.extraSpecialArgs to pass
              # arguments to home.nix
              extraSpecialArgs = commonExtraSpecialArgs;
              backupFileExtension = "backup";
              sharedModules = [
                # mac-app-util.homeManagerModules.default # FIXME: permission issues.
              ];
              users.alex.imports = [
                ./users/alex/NIXY/home-NIXY.nix
              ];
            };
          }
          agenix.darwinModules.default
        ];
      };
    };
  in
  {
    # Return all the configurations
    nixosConfigurations = nixosConfigurations;
    darwinConfigurations = darwinConfigurations;
    # FIXME: add nixvim here so I can build from any device without installing the dotfiles.
  };
}

```

my macOS version:
14.7
home-manager version:
I'm not entirely sure... 23.05 or 24.05

also, my .dotfiles config for reference (I'll push my changes)
https://github.com/aspauldingcode/.dotfiles

**Comment by hraban** [comment] 2024-10-30 19:01
Thanks I'll have to try on a VM because I never actually use bare HM. Can you give me a pared down version of your flake to help my debugging journey along? :)

**Comment by aspauldingcode** [comment] 2024-10-30 19:40
Oh boy, I'll try... gimme several hours until I'm home. 😁

**Comment by aspauldingcode** [comment] 2024-10-31 02:40
Hi...

I'm not entirely sure the best way to do that so I've tried minimizing the amount of things in the flake to just the essentials, I wonder if it will work for you:


```

{
  description = "Minimal Flake for macOS with nix-darwin and mac-app-util";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05"; # Set stable version
    nix-darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs"; 
    };
    home-manager = {
      url = "github:nix-community/home-manager/release-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    mac-app-util = {
      url = "github:hraban/mac-app-util";
    };
  };

  outputs = { self, nixpkgs, nix-darwin, home-manager, mac-app-util }:
    let
      # Define common arguments for home-manager and nix-darwin
      specialArgs = {
        inherit nixpkgs nix-darwin home-manager mac-app-util;
      };
    in {
      darwinConfigurations = {
        macSystem = nix-darwin.lib.darwinSystem {
          system = "aarch64-darwin";
          pkgs = import nixpkgs { system = "aarch64-darwin"; };

          specialArgs = specialArgs;

          modules = [
            ./system/macSystem/darwin-configuration.nix
            mac-app-util.darwinModules.default
            home-manager.darwinModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                users.alex.imports = [ ./users/alex/macSystem/home.nix ];
              };
            }
          ];
        };
      };
    };
}

```

**Comment by aspauldingcode** [comment] 2024-10-31 02:40
I haven't tried that on my system but it fails if I install `vscode` or `vesktop` in home-manager, and pass in the module for mac-app-util as a home-manager module

**Comment by hraban** [comment] 2024-11-01 21:25
I tried with this flake.nix on a completely fresh installation and couldn't reproduce the issue:

```
{
  description = "Minimal Flake for macOS with nix-darwin and mac-app-util";

  inputs = {
    mac-app-util.url = "github:hraban/mac-app-util";
  };

  outputs = { self, nixpkgs, home-manager, mac-app-util, ... }: let
    username = "user";
    system = "aarch64-darwin";
  in {
    homeConfigurations.${username} = home-manager.lib.homeManagerConfiguration {
      pkgs = import nixpkgs { inherit system; config.allowUnfree = true; };
      modules = [
        mac-app-util.homeManagerModules.default
        ({ pkgs, ... }: {
          home = {
            inherit username;
            homeDirectory = "/Users/${username}";
            packages = [
              # I replaced this with other apps, readded vscode, etc; no problems
              pkgs.vscode
            ];
            stateVersion = "24.05";
          };
        })
      ];
    };
  };
}
```

Used `nix run home-manager -- switch --flake .` to enable the config and found no problems.

If you can take this and turn it into a reproducible example I can help you further.

**Comment by hraban** [comment] 2024-11-12 04:05
I added a sample config for home-manager without flakes in the README. This also worked in a VM.

I'm going to close this issue because I can't reproduce it but if you (or someone else) has more info for reproducing the error please feel free to post it here and reopen.

**Closed by hraban** 2024-11-12 04:05 UTC
Labels: cannot-repro

**Comment by aspauldingcode** [comment] 2024-12-09 05:46
@hraban  I've done a fresh install of macOS, and it seems to be working perfectly fine now. Must've had a borked system before. Maybe it had to do with my custom rsync functions I had in nix-darwin and home-manager in extraActivation scripts.
