### ISSUE TITLE
Can't open Kitty via spotlight

### ISSUE THREAD

**Issue by HPRIOR** [hraban/mac-app-util#13] opened 2024-11-24 11:41 UTC
There is an app that works in nixpkgs, but not when using mac-app-util. Its name is: kitty

It is not broken in nixpkgs proper, because I can `nix build` it successfully

And I can launch it via the terminal using `kitty &`

When I try to launch kitty via spotlight I am getting the error:

```
_LSOpenURLsWithCompletionHandler() failed with error -54
```

My system:

```
$ nix-info -m

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/ly4s3hw35dd1c2vsd694y2715pc1d2c1-source`
....
```

I'm using the module like so:
https://github.com/HPRIOR/nix-config/blob/9d7f03002a73de65d547530c2ee2085cb845e139/flake.nix#L166

**Comment by hraban** [comment] 2024-11-25 06:05
Kitty has an upstream problem which is fixed in nixpkgs-unstable.

Dupe of #8 and #11

**Closed** 2024-11-25 06:05 UTC
Labels: invalid

**Comment by mstarodub** [comment] 2025-03-07 13:16
I'm experiencing this issue on Sequoia 15.3.1 and mpv. (mpv 0.39.0, built on Mar  4 2025 21:10:46)

`_LSOpenURLsWithCompletionHandler() failed with error -54. (1)`

possibly relevant: https://github.com/NixOS/nixpkgs/pull/265529

Any ideas?

**Comment by hraban** [comment] 2025-03-07 14:07
@mstarodub the conclusion of this issue we're responding to right now is that it is a valid problem, but this is the wrong project to report it to. If a package is broken on nixpkgs, then installing that package using mac-app-util will still be broken. So if you're facing the same problem now with mpv that the original reporter of this issue was facing with kitty at the time, the response from me will be: wait until it's fixed in nixpkgs.

Is that a fair assessment of your problem or is there something else going on?

**Comment by mstarodub** [comment] 2025-03-07 14:14
Thanks, and sorry for the noise. I found this issue after posting my comment: https://github.com/NixOS/nixpkgs/issues/356860

**Comment by hraban** [comment] 2025-03-08 08:55
No worries. As much as I hate to admit it, most questions like these are indicative of lacking documentation or poor error handling. If it keeps happening I'll need to figure out a way to make this clearer from the readme , the issue template, or the error message.

Good luck!
