### ISSUE TITLE
Trampoline script is busted on MacOS 15.1

### ISSUE THREAD

**Issue by kriswill** [hraban/mac-app-util#11] opened 2024-11-10 19:40 UTC
On MacOS Sequoia 15.1, Apple is now enforcing the Gatekeeper requirement for all ".app" files to include code signing for the darwin-aarch64 platform.  Launching app binary directly from the Mac Terminal seems to work fine, but the Finder and Dock do not work. You'll see some friendly errors like this:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/70560110-1bb1-4c15-a62e-65c66d1fe5ae">

The affected code:
https://github.com/hraban/mac-app-util/blob/9c6bbe2a6a7ec647d03f64f0fadb874284f59eac/main.lisp#L154

**Comment by hraban** [comment] 2024-11-11 01:14
Hi, I'm afraid I was unable to reproduce this on my own Mac 15.1, both on bare metal and in a VM. Do you have a reproducible example?

**Comment by kriswill** [comment] 2024-11-11 08:08
I'm not sure how I can make this reproducible without significant effort.  However, there is slightly different behavior when running it from the spotlight menu.  For example, with kitty:
<img width="812" alt="image" src="https://github.com/user-attachments/assets/6c7a8dd5-e0fd-4b1b-b92f-c2be84ec31ac">
I've found other people with self-compiled mac apps complaining about this in some of the other corners of searching [forums](https://forums.macrumors.com/threads/finder-does-not-have-permission-to-open-null.2441374/?post=33535657#post-33535657).  I'm not sure if that is helpful or not.  You can see my whole nix-darwin setup on this [branch](https://github.com/kriswill/dotfiles/tree/nix-darwin) - it lags behind my nixos config by a few months...

**Comment by hraban** [comment] 2024-11-11 20:02
I believe it, I just don't know where to start debugging this without a reproducible issue. I'll leave this open for a bit just in case someone else has the same problem but aside from that it's hard for me to work on an issue I don't have :/

**Comment by felixzieger** [comment] 2024-11-11 22:44
I think this needs to be fixed in nixpkgs. Example for Kitty: https://github.com/NixOS/nixpkgs/pull/352795

**Comment by hraban** [comment] 2024-11-12 01:56
ah so it's a dupe of this one https://github.com/hraban/mac-app-util/issues/8 thanks @felixzieger !

**Closed by hraban** 2024-11-12 01:56 UTC
Labels: cannot-repro
